### ISSUE TITLE
Package description identical to cottz-publish

### ISSUE THREAD

**Issue by dandv** [Goluis/cottz-publish-relations#1]
https://atmospherejs.com/cottz/publish-relations
https://atmospherejs.com/cottz/publish

Both are described as "Edit your documents before sending without too much stress".

**Comment by lfades** [comment]
the 2 packages are different and have a different Api, the package I'm using is cottz-publish-relations because it is simpler (in code and usability)

**Comment by dandv** [comment]
I see this on https://atmospherejs.com/cottz/publish

> NOTE: this package is now called cottz:publish-relations and is hosted on https://github.com/Goluis/cottz-publish-relations

Authors who no longer wish to maintain a package can hide it from Atmosphere search results while still letting the package be installable by existing apps and dependent packages by running

```
meteor admin set-unmigrated <package_name>
```
