### ISSUE TITLE
this.join unexpected behaviour

### ISSUE THREAD

**Issue by kristiankyvik** [Goluis/cottz-publish-relations#12]
So I first implemented reactive join using the example for the quick start you included in the README.md. 

```
  this.cursor(Chatter.Room.find({ _id: roomId }, roomFilter), function (id, room) {
    this.cursor(Chatter.UserRoom.find({ roomId }, userRoomFilter), function (id, userRoom) {
      this.cursor(Meteor.users.find({ _id: userRoom.userId }, userFilter), function (id, user) {
      });
    });
  });
```

And this works marvellously. Then I try optimise this publish function using this.join() and this.send() like the following:

```
let users = this.join(Meteor.users, userFilter);
  let count = 0;
  this.cursor(Chatter.Room.find({ _id: roomId }, roomFilter), function (id, room) {
    this.cursor(Chatter.UserRoom.find({ roomId }, userRoomFilter), function (id, userRoom) {
      users.push(userRoom.userId);
    });
  });
  users.send();
```

And after adding and removing userRoom, which connect users and rooms, this version of the publication does not return the correct users. Am I missing something?

Thanks in advance for your help!

**Comment by lfades** [comment]
`this.join` makes a query in the format `{_id: {$in: [_ids]}}`. Keeping that in mind every time that a `UserRoom` is removed PublishRelations doesn't remove the user because it means make the same query with a less Id (if you need to remove the user, you can do it in another way). But ¿what is the error when you're adding a `UserRoom` ?

**Comment by kristiankyvik** [comment]
Hi, and thanks for answering. Essentially what I have is Chatter.Rooms and users, which are linked together using Chatter.UserRoom. Simplified version of it here:
```
Chatter.Room = {
 _id: "XXXXXxXXX"
};

User = {
 _id: "XXXXXxXXX"
};

Chatter.UserRoom = {
 _id: "XXXXXXXX",
 userId: "XXXXXXX", // id of a user 
 roomId: "XXXXXXX"  // id of a room
}
```
Before moving to your package I was using the publishComposite package with something like this:

```
Meteor.publishComposite('roomData', function (roomId) {

  return {
    find: function () {
      return Chatter.Room.find({ roomId },
        {}
      );
    },
    children: [
      {
        find: function (room) {
          return Chatter.UserRoom.find({roomId: room._id},
            {}
          );
        }
      }
    ],
      children: [
      {
        find: function (userRoom) {
          return Meteor.users.find({roomId: userRoom.userId},
            {}
          );
        }
      }
    ]
  };
});
```

This guaranteed reactivity when deleting and creating new userRoom instances that linked users with rooms. However, because of performance I wanted to avoid looping and making several find calls, and instead collect the id and call them at the end, which is what I was trying to do using your package and the this.join() and this.send() api.

However, I dont get reactivity when I tried it. Maybe I am misunderstanding the  methods, in that case, do you have any suggestion to hoy I can implement this using your package in an effective way?

**Comment by lfades** [comment]
I'm not cloning the query, and when I add a new Id (push), a future validation of not to repeat the query in case the selector is equal is always true. Really has never served me that validation, especially because it is better not have to get to need it, I'll eliminate it and your problem is solved.

**Comment by kristiankyvik** [comment]
Goluis, thanks for your response. Just to make sure I have understood. Does this mean you are going to make a change to the package as a whole that will fix this problem and making the code below work as I want it to work?

```
let users = this.join(Meteor.users, userFilter);
  let count = 0;
  this.cursor(Chatter.Room.find({ _id: roomId }, roomFilter), function (id, room) {
    this.cursor(Chatter.UserRoom.find({ roomId }, userRoomFilter), function (id, userRoom) {
      users.push(userRoom.userId);
    });
  });
  users.send();
```

**Comment by lfades** [comment]
Yes, also, as a performance upgrade, use this
```js
this.cursor(Chatter.Room.find({_id: roomId}), function (id, room, changed) {
  // don't call this.cursor again every time that the room change
  if (!changed) {
    this.cursor(Chatter.UserRoom.find({roomId}), function (id, userRoom) {
      users.push(userRoom.userId)
    })
  }
})
```
or you can also do this:
```js
this.cursor(Chatter.Room.find({_id: roomId}), {
  added (id, room) {
    this.cursor(Chatter.UserRoom.find({roomId}), function (id, userRoom) {
      users.push(userRoom.userId)
    })
  }
})
```

**Comment by kristiankyvik** [comment]
Thank you so much Goluis! I will mark the issue as closed!

**Comment by lfades** [comment]
I published the repo that I used to fix the problem here:
https://github.com/Goluis/meteor-publish-relations-join-test

maybe it can help you in something :D
