### ISSUE TITLE
Is 'this.ready()' obligatory?

### ISSUE THREAD

**Issue by vbgm** [Goluis/cottz-publish-relations#16]
The publication seem to work without `this.ready()`, but in documentation it is provided as example. Is this obligatory?

**Comment by lfades** [comment]
From docs:
```js
// you can do this to finish writing your publication
this.ready();
return this.ready();
return [];
return [cursor1, cursor2, cursor3];
```

**Comment by vbgm** [comment]
I have seen this, it is just it seems that my publication works even if I do not add anything of the above.

**Comment by lfades** [comment]
if the publication finished properly and you don't see any memory leak, then it's okay.

**Comment by vbgm** [comment]
My mistake, I have used a wrapper and did not notice it was added by me.
