### ISSUE TITLE
Help Plz: Filter/remove some documents from a this.cursor() - call?

### ISSUE THREAD

**Issue by DanielDornhardt** [Goluis/cottz-publish-relations#3]
Hello,

i'm rewriting parts of my app using cottz-publish-relations and it's going great so far! :D

But now I've come across a situation where I'm stumped and don't know how to handle it.

The task is the following:

I've got an Activity Stream (think Facebook wall) and objects which are published (let's say "stories").

But some of those stories should be private, or maybe only visible for certain people / groups. To keep  this example simpler, let's say they're private and should only be visible for the user themselves, but not for others.

For the users themselves this is easy:

```
this.cursor(Activities.find({}, {sortBy: {timestamp: -1}})), function(activityId, activityDoc) {
  if (activityDoc.storyId) {
    this.cursor(Stories.find({activityDoc.storyId}));
  }
});
```

Or something similar to this, right? (Pseudocode, untested).

But what if I want to decide whether to publish an Activity only if the Story has some kind of flag set (let's say "public")?

How can I remove the activity from the Activities.find() - result while keeping everything reactive?

If I'd first query all activity IDs and then make a {_id: {$in: [storyIds]}} - query on the stories, new activities wouldn't be published after that, right?

And the other way round, if I'd first get all the stories to filter by those, I'd potentially have a million stories in my cursor and only 5 related to the activity stream, which could produce a big overhead I think.

---

Actually I had one idea now: I could "nerf" the Activities for the "private" stories by unsetting / setting to undefined the fields I don't want the client to receive (I don't want to publish the stories' ids if they are private).

But is there a straightforward way to do this? I couldn't think of any.

One other solution I could think of would be to combine cottz-publish-relations with some other server side reactivity package and use a tracker to rerun the publication when some criteria of them change - does anybody have a good pattern / experience with this?

Thanks and best wishes

Daniel

**Comment by lfades** [comment]
before help with a solution let me know if I understood what you need.

`But some of those stories should be private, or maybe only visible for certain people / groups. To keep this example simpler, let's say they're private and should only be visible for the user themselves, but not for others.`
- Want to post activities with stories that are public?

`But what if I want to decide whether to publish an Activity only if the Story has some kind of flag set (let's say "public")?`
- Want to post activities only if the stories are public?

**Comment by DanielDornhardt** [comment]
Exactly. I want to post activities only for stories which are public.

Or in the abstract:
- Publish from a Collection A only those documents where in a document from a Collection B some condition is true. A references B, like A.id_collectionB -> collectionB-Document._id . Can I reactively publish Collection A with some documents filtered out?

**Comment by lfades** [comment]
I suppose your collection A are the activities and your collection B are the stories
according to this publication

``` js
this.cursor(Activities.find({}, {sortBy: {timestamp: -1}})), function(activityId, activityDoc) {
  if (activityDoc.storyId) {
    this.cursor(Stories.find(activityDoc.storyId));
  }
});
```

you only have a story for each activity. It would be best to keep the public status within the activity and can solve the problem before moving to find stories.

If the above is not possible other solution could be to use `this.observeChanges` and send the changes manually only if you find stories, but you would have performance problems because even if you do not send some activities continue to have an observer on them, it would be best to solve the problem by checking the Activities document

**Comment by DanielDornhardt** [comment]
Ah, I see, using this.observe / this.observeChanges inside of my publish lets me monitor a collection without publishing it? Yes, that'd probably what I need. I think it'll be efficient enough for my use case, at least it'd scale linearly with the number of activities selected and not with the total number of stories (which could become quite large).

Thanks for the clarification, I'll try it that way!
