### ISSUE TITLE
one to many relationship

### ISSUE THREAD

**Issue by Ajaxsoap** [Goluis/cottz-publish-relations#4]
Hi,

Thanks for creating this package!

I tried different package for the relation but it seems that none of them wasn't able to solved my problem.

Here's the problem:
I have two collections, `enrollments` and `claims`
on my enrollments collection I have this fields:
`fullName, products, childrenName, children2, children3, parents and siblings`

on my claims collection I have this:

`Principal` - fullName from enrollments collection
`Dependent-Children` - childrenName, children2 and children3 from enrollments collection which is not an arrray, they are individual fields.

How do you setup the publish function for this scenario? Wherein the available `childrenName` is based on the `enrollmentId` field that the user select. Currently, all the `childrenName` is being populated from enrollments collection.

On my current set up on template claims form, I have select element which populated by fullName from my claims schema like this:

```
enrollmentId: {
    type: String,
    label: "Principal Name",
    autoform: {
      firstOption: 'Select Principal Name',
      options: function () {
        return Enrollments.find( {}, {
          sort: {
            fullName: 1
          }
        } ).map( function ( enrollmentId ) {
          return {
            label: enrollmentId.fullName,
            value: enrollmentId._id
          };
        } );
      },
      afFormGroup: {
        'formgroup-class': 'col-xs-6 col-sm-4'
      }
    }
  },
```

and here's on my  children schema:

```
children: {
    type: String,
    label: "Dependent-Children",
    optional: true,
    autoform: {
      firstOption: 'Select Children',
      options: function () {
        var formId = AutoForm.getFormId();
        var enrollment = AutoForm.getFieldValue( 'enrollmentdId', formId );
        var child = Enrollments.find( {
          chidlrenName: enrollment
        }, {
          sort: {
            childrenName: 1
          }
        } ).map( function ( children1 ) {
          return {
            label: children1.childrenName,
            value: children1._id
          };
        } );
        console.log( child );
        return child;
      },
      afFormGroup: {
        'formgroup-class': 'col-xs-6 col-sm-4'
      }
    },
  },
```

`enrollmentId` is working as expected, the select element is populating with all the `fullName` field from enrollments collection but the the problem is on the `childrenName` it's populating all the children from other documents, it's supposed to be the children of the Princapal. I will referenced this [thread](https://forums.meteor.com/t/dependant-drop-down-list/8192/12) for additional info.

Thanks in advance.

**Comment by lfades** [comment]
so I understood you want to publish one or more enrollments and publish their claims

``` js
Meteor.publishRelations('enrollments', function (enrollment) {
    let cursor = Enrollments.find({childrenName: enrollment}, {sort: {childrenName: 1}});

    this.cursor(cursor, function (id, doc) {
        this.cursor(Claims.find({_id: {$in: [doc.childrenName, doc.children2, doc.children3]}}));
    });

    return this.ready();
});
```

if the code is incorrect or not let me know

**Comment by Ajaxsoap** [comment]
Thanks @Goluis for your time!

Yeah, to make it simple, on claims collection I should have `fullName`(enrollmentId) and it's corresponding `childrenName` from enrollments collection. 

Desired scenario, use case, on my claims form, i have a `enrollmentId` dropdown list, since the claim is for the dependent children, based on the chosen `enrollmentId`, on `childrenName` dropdown list it should only be the children of the chosen enrollmentId is available. The selection `childrenName` should be from the same document (same _id).

My current setup is that all the childrenName from other documents is being passed :(

**Comment by lfades** [comment]
It is quite likely that I still don't understand

the `Claims` form show all the `Enrollments`, so you have a publication like this I guess

``` js
Meteor.publish(function () {
  return Enrollments.find({}, {sort: {fullName: 1}})
})
```

the user selects an `Enrollment` and then subscribe to his `Claims`

``` js
Meteor.publish('enrollments', function (childrenName) {
    // this is the part I do not understand
    return Claims.find({childrenName: childrenName})
})
```

**Comment by Ajaxsoap** [comment]
The user which is one of the  staff in an insurance company, enrolled (create enrollment) a certain `John Doe` (fullName) with his 3 kids(children), assuming this John Doe filed a claim (claims collection) for his kid(children from Enrollments collection). The user will create a claim selecting John Doe as the principal and select John Doe's kid as the dependent. 

Given the context of John Doe, the children selection is limited to only his child not all children from other enrollee. Am I making any sense?

This is my current publication:

```
Meteor.publish(function () {
  return Enrollments.find();
})
```

on creating a claim, the user subscribe to Enrollments:

```
Meteor.publish('claimEnrollment', function() {
   // fields fullName, children
   return Enrollments.find({},{fields: {fullName: 1, childrenName: 1, children2: 1}});
});
```

I'm having a hard time making this to work, even using `reactiveVar` to `set` and ``get` the id of John Doe, the selection is always populated with all the child on the collection.

**Comment by lfades** [comment]
the following publication should return all `Enrollments` or a single enrollment with his children `Claims`

``` js
Meteor.publishRelations('test', function (fullName) {
  check(fullName, Match.Optional(String));

  if (!fullName)
    return Enrollments.find();

  // {fullName} = {fullName: fullName}
  let cursor = Enrollments.find({fullName}, {fields: fullName: 1, childrenName: 1, children2: 1}})

  this.cursor(cursor, function (id, doc) {
    this.cursor(Claims.find({
      principal: fullName,
      dependent: {$in: [doc.childrenName, doc.children2]}
    }))
  })

  return this.ready()
})
```

I'm closer to the solution?

**Comment by Ajaxsoap** [comment]
Thanks so much @Goluis for sharing your expertise!

I think this will work, as I can see it's in the document level :) 

I will try this and get back to you! 

:+1:

**Comment by lfades** [comment]
Importantly: `PublishRelations` uses a basic [observeChanges](http://docs.meteor.com/#/full/observe_changes). `doc` is only the complete document when sending the first time, then he only has the changes, is likely to lose reactivity when the document change, luckily there are many quick ways to fix it.

This method is quite good but is somewhat complex

``` js
let children = [];
this.cursor(cursor, function (id, doc) {
  if (doc.childrenName || doc.children2) {
    if (doc.childrenName)
      children[0] = doc.childrenName
    if (doc.children2)
      children[1] = doc.children2

    this.cursor(Claims.find({
      principal: fullName,
      dependent: {$in: children}
    }))
  }
})
```

using this.join

``` js
let children = this.join(Claims)
children.selector = names => {principal: fullName, dependent: names}
/*children.selector = function (names) {
  return {
    principal: fullName,
    dependent: names
  }
}*/
this.cursor(cursor, function (id, doc) {
  children.push(doc.childrenName, doc.children2)
})
children.send()
```

If the children never change this would be the ideal method

``` js
this.cursor(cursor, {
  added (id, doc) {
    this.cursor(Claims.find({
      principal: fullName,
      dependent: {$in: [doc.childrenName, doc.children2]}
    }))
  }
})
```

I recommend you see the last part of the documentation, it has a lot of useful information ^^

**Comment by thearabbit** [comment]
Excuse me, I don't understand how to get `doc of Claims`.
(We can get it automatic in  `Enrollments` or not)

**Comment by lfades** [comment]
@thearabbit  the package makes relationships, but cursor sends all documents to their respective collection, to pick up the document use a callback:

``` js
// send all users
this.cursor(Meteor.users.find()); 

// send all users with a new key in the document
this.cursor(Meteor.users.find(), function (id, doc) {
  doc.something = true;
});
```

**Comment by thearabbit** [comment]
Thanks I will try.
