### ISSUE TITLE
Need help getting started

### ISSUE THREAD

**Issue by ickyrr** [Goluis/cottz-publish-relations#5]
Suppose I have multiple collections, in this case, I have 3 collections I want to join.

Clicks: {
  country: "anywhere",
  agent_id: "someAgentId",
  campaign_id: "someCampaignId",
}

Users //from Meteor.users collection
 {
  _id: "someUserId", --> this is the one attached as 'agent_id' to Clicks
  roles: 'agent',
  username: 'usernameHere'
 }

 Campaign: {
  _id: "someCampaignId", --> attached as 'campaign_id' to Clicks
  name: "someCampaignName"
 }

 Let's say I have 100 Clicks.

 How Can I make it look like this in a table:

 ================================
 country    | agent   | campaign
 ================================
 anywhere| Joe      | GoogleCampaign
 anywhere| John    | BingCampaign
 anywhere| Vic       | FBCampaign
 anywhere| Mike    | TwitterCampaign
 =================================

 Notice that instead of displaying the 'agent_id', I want to display the name of the agent.
 Just starting out with meteor and encountered this problem. Hope you could help me out.

**Comment by lfades** [comment]
``` js
Meteor.publishRelations('clicks', function (country) {
  let users = this.join(Meteor.users),
  campaings = this.join(Campaings)

  this.cursor(Clicks.find({country}), function (id, doc) {
    users.push(doc.agent_id)
    campaings.push(doc.campaing_id)
  })

  users.send()
  campaings.send()

  return this.ready()
})
```

Explanation: If you have 100 clicks, will make a query to find 100 clicks, then keep all _ids and will consult in other collections. in total they would be three queries to the database and should be quick and effective

**Comment by ickyrr** [comment]
Thanks for responding right away @Goluis , just a quick question, would this also help the devs out when building a project which handles large amount of data?

**Comment by lfades** [comment]
yes, that was one of the reasons why I create the package, needed an easy way to create complex queries on the server for my application

**Comment by ralphievolt** [comment]
@Goluis  @ickyrr 

I followed the above example to join multiple collections which seems to work... In my client I can see  two collections which I can use..

My problem is how to show the name instead of an Id..here's my code in REACT

```
{ this.props.subCatList.map((item,index) => (
      <tr key={index}>
             <td>{item.subcategory}</td>       
        
             <td>{item.categoryID}</td>
             
             <td>{item.created.by}</td>
             <td>
                  <button className="ui blue basic mini button" value={item._id} onClick={this._handleItemClick(event)} >{item.status}</button>
             </td>
       </tr>
    )
)}
```
Am I missing something here? Am I supposed to receive only one subscriptions with my categoryName instead of categoryID?

**Comment by lfades** [comment]
@ralphievolt I didn't quite understand what you're trying to say, but I'm going to assume that you want to display the name of a document in a different collection based on the id.

```js
function getName (_id) {
  return collection.find({_id}).fetch()[0].name;
}

{this.props.subCatList.map((item, index) => (
  <tr key={index}>
    <td>{item.subcategory}</td>       

    <td>{item.categoryID}</td>
     
    <td>{item.created.by}</td>
    <td>
      <button className="ui blue basic mini button" value={getName(_id)} onClick={this._handleItemClick(event)} >{item.status}</button>
    </td>
  </tr>
)}
```

Remember that although the package does joins, it does not mix the documents.

**Comment by ralphievolt** [comment]
i wanted to see the category name  instead of  `<td>{item.categoryID}</td>`

anyway, i'll try creating a new component based on your answer and see if I can get it working
