### ISSUE TITLE
Trying this.listen example

### ISSUE THREAD

**Issue by knoid** [Goluis/cottz-publish-relations#9]
I'm trying to use the same approach as the example that uses `this.listen` but the publication throws `Match failed` upon startup. I can see that you do a `Meteor.publish` without arguments in the client so that may be throwing.

Have you tried your example? Does it work like this?

**Comment by lfades** [comment]
oh right, when you subscribe on the client you must send an object as the second parameter. (or the match at the beginning of the publication will fail).

``` js
Meteor.subscribe('books', {authorId: 'authorId', skip: 10});
```

I'll fix it soon.
